### ISSUE TITLE
exportSessionVariables in writeBashScript looks misplaced

### ISSUE THREAD

**Issue by ip1981** [zalora/microgram#50]
`exportSessionVariables` in `writeBashScript` looks misplaced:

- not every bash script needs it
- `platform/runtimes/angel.nix` seems to be a better place along with `LOCALE_ARCHIVE`

**Comment by proger** [comment]
`exportSessionVariables` look pretty strategically placed. That macro was about explicitly importing things that are made implicit my `/etc/profile.d`-like global variables in other awful operating systems.

**Comment by ip1981** [comment]
When I see the name `writeBashScript` or `writeFooScript` I expect it to write down what I tell it to write and nothing more. For `exportSessionVariables` we need another function. And I think we should wrap every piece of an app (service, cli, wtf, etc.) into app environment. And as @4z3 told, they are not have to be bash scripts.

**Comment by proger** [comment]
It's kind of a tradeoff, it's quite common for a `writeBashScript`-produced script to either use HTTPS or access locale data (which is what `exportSessionVariables` used to export)

**Comment by proger** [comment]
It's not like we're putting our phone numbers and a list of meat restaurants just in case.

**Comment by ip1981** [comment]
it's even more common to use coreutils, findutils, sed, grep, and other nice tools.

**Comment by proger** [comment]
Your point being?

**Comment by ip1981** [comment]
IOW, `writeBashScript` would be a wrong name for this thing with `exportSessionVariables`.

We got `writeBashScript'` for transition, and we should wrap every executable, no matter bash or haskell, or perl, or ruby, something like `startSession env executable`. We do it in angel services already, but will need it everywhere, including CLI.

**Comment by ip1981** [comment]
https://github.com/zalora/microgram/commit/e2ecc0fa1bc2d60a59a70ef316d468fe9086632f
